# Figure 3 Legend {.unnumbered}

**Figure 3. Integrated single-nuclei profiling identifies distinct tumor associated microglia/macrophages in astrocytoma and oligodendroglioma.** (**A**) UMAP representation of the integrated microglia cluster obtained from snRNA-seq data primary oligodendroglioma and astrocytoma tumors. (**B**) Bar plots depicting the proportions of microglia subpopulations identified by snRNA-seq, separated by patient, tumor type and LGG grade. (**C**) Box plots displaying the differential proportion of microglia subpopulations across tumor type. Significance of the difference in proportions is tested by applying an unpaired Wilcoxon rank-sum test. (**D**) Representative IHC staining for tumor-associated microglia markers IBA1, CD74, CD163 and double staining for phospho-STAT1 (p-STAT1) and IBA1 shown for oligodendroglioma and astrocytoma samples. (**E**) Bar plots of semi-quantitative histological scores (0 = 0, 1 = 0-5%, 2=6-29%, 3=30-69%, 4=\>70% of positive staining) for p-STAT1+IBA1+ microglia in oligodendroglioma (OD) and astrocytoma (AS) separated by grade (G) (n = 3 per group). (**F**) Selected receptor-ligand interactions between the OPC-like and astro-like tumor cells and the microglia subpopulations. Significance of the interactions is encoded by the dot size and the magnitude (defined as the log2 of the average expression of the ligand and the receptor pairs) by the color.
