# Figure 4 Legend {.unnumbered}

**Figure 4. Single-nuclei profiling of paired primary and recurrent astrocytomas indicate shifts in tumor populations associated with grade.** (**A**) Metadata including clinical and molecular characteristics of paired primary and recurrent IDH mutant astrocytoma cohort for single-nuclei RNA-seq. (**B**) UMAP representation of the integrated snRNA-seq data from paired astrocytoma tumors. (**C**) Bar plots depicting the proportions tumor clusters grouped by the primary/relapse pairs, LGG grade and relapse status. (**D**) Representative IHC staining for two RA population marker genes EEF2 and eEF1A1 for paired primary (grade 2) and relapse (grade 3) astrocytoma. (**E**) Heatmap showing semi-quantitative eEF1A1 histological scores (0 = 0, 1 = 0-5%, 2 = 6-29%, 3 = 30-69%, 4 =\> 70% of positive staining) for 6 pairs of primary (P) and recurrent (R) oligodendroglioma (OD) and astrocytoma (AS). eEF1A1 shows a significant increase in relapsed astrocytomas. Wilcoxon signed-rank test for paired samples was performed to test for significance, \* indicates p \< 0.05. (**F**) UMAP representation of the integrated microglia clusters of paired primary and recurrent IDH mutant astrocytoma cohort, colored by microglia subpopulations (top left), relapse status (top middle and right) and tumor grade (bottom). (G) Box plot depicting the proportions of microglia subpopulations, grouped by primary/relapse pairs, relapse status and tumor grade. (H) Box plot of the proportions of microglia subpopulations split by relapse status. Significance of the difference in proportions is tested by applying a paired Wilcoxon rank-sum test.
