# Figure S7 Legend {.unnumbered}

**Fig. S7.** **Presence of RA tumor population in external datasets**. Datasets from *Venteicher, et al.* (**A**) and *insert later* (**B**) are used. UMAP representation of the tumor cells is shown together with the enrichment scores for RA metaprogram. (top left and middle). The distribution of enrichment scores is tested for normality using Shapiro test (bottom left) and the value so that the probability of finding a enrichment score higher is 5% is used to select the RA cells. The activity of the different cell clusters and the RA population towards the NMF metaprograms and the programs from *Venteicher, et al.* is computed by using *decoupleR*. Activity scores are scaled and centered and displayed grouped by cell population (bottom middle). To query the robustness of RA metaprogram towards the RA population, 50 different gene sets of equal length are generated by randomly selecting genes in the same bin of expression as the genes in the RA metapgroam. Activity scores are computed, scaled and centered, and displayed grouped by cell population.
