# Figure 1 Legend {.unnumbered}

**Figure 1. Identifying meta gene expression programs driving cell states in IDH mutant gliomas.** (**A**) Metadata including clinical and molecular characteristics of IDH mutant glioma cohort for single-nuclei sequencing. Samples subjected to single-nuclei RNA (snRNA) or/and single-nuclei ATAC (snATAC) sequencing are indicated. (**B** and **C**) UMAP representation and initial cluster assignment for integrated snRNA-seq samples of oligodendroglioma (**B**) and astrocytoma (**C**). Colors represent assigned cell types. (**D** and **E**) Pearson's correlation scores for individual NMF programs identified by unsupervised NMF analysis in oligodendrogliomas (n = 8) (**D**) and astrocytomas (n = 6) (**E**). Metaprograms corresponding to OPC-like, astro-like, cycling and ribosomal active (RA) phenotypes were identified by hierarchical clustering of individual NMF programs. (**F** and **G**) Clusters assigned to respective cell states in oligodendrogliomas (**F**) and astrocytomas (**G**). (**H**) Dot plot showing five shared key marker genes from the top 30 differentially expressed genes for each tumor population in both oligodendrogliomas and astrocytomas. (**I**) Bar plot of the proportions of each tumor population across individual samples. Bars are ordered first by LGG subtype, then by descending RA proportion. Summarized proportions per tumor grade and LGG subtypes are also displayed. (**J**) Representative IHC staining for H&E and two RA population marker genes EEF2 and eEF1A1 for oligodendroglioma and astrocytoma samples separated by grade. (K) Plots show semi-quantitative histological scores (0 = 0, 1 = 0-5%, 2=6-29%, 3=30-69%, 4=\>70% of positive staining) for EEF2 (top) and eEF1A1 (bottom). top, a qualitative increase in EEF2 staining in grade 3 compared to grade 2 astrocytomas; bottom, a qualitative increase in EEF1A1 staining in grade 2 oligodendrogliomas compared to grade 2 astrocytoma. Wilcoxon rank-sum test was performed to test for significance, \* indicates p \< 0.05.
