# Figure 2 Legend {.unnumbered}

**Figure 2. Integrated snRNA-seq and snATAC-seq indicates a stemness enriched signature in the ribosomally active tumor cluster.** (**A**) Diffusion map visualization of oligodendrogliomas and astrocytomas computed based on the genes reported for the Astrocyte-like, Oligo-like and Stemness programs in *Venteicher, et al.* Right:Scaled and centered enrichment scores for the three programs. Cells are ordered based on their position along diffusion component 2 (DC_2). Gradient cells are excluded for better visualization. RA cells locate at one end of DC_2, where the enrichment for Stemness program is highest, suggesting stemness-like properties of RA cells. (**B**) Scaled and centered pathway activity scores for oligodendrogliomas (right) and astrocytomas (left), grouped by tumor clusters. (**C**) Scaled and centered regulon (transcription factor and downstream targets ) activity scores for oligodendrogliomas (bottom) and astrocytoma (top), grouped by tumor clusters. (**D** and **E**) UMAP projections of oligodendroglioma (**D**) and astrocytoma (**E**) snATAC-seq data colored by the labels transferred from the single-cell transcriptomics datasets. (**F** and **G**) Pearson correlation between the promoter accessibility counts across tumor clusters in oligodendroglioma (**F**) and astrocytoma (**G**). (**H**) Pearson correlation between 1764 transcription factor motifs across tumor clusters in oligodendrogliomas. (**I**) Heatmap showing the top significantly enriched transcription factor motifs (max n = 20 per cluster) in oligodendrogliomas. Significant motifs in the RA cluster are highlighted. (J) Violin plot showing the scores significantly enriched transcription factor (TF) motifs with average log2 fold change \> 1 in the RA cluster in oligodendrogliomas. OD, oligodendroglioma; AS, astrocytoma
