# Figure S20 {.unnumbered}

```{r}
#| echo: false
#| message: false
#| warning: false
#| error: false
source("../_common.R")
suppressMessages(suppressPackageStartupMessages(library("Seurat")))
suppressMessages(library("magrittr"))
```

```{r}
#| message: false
#| warning: false
#| error: false
# Enrique Blanco Carmona
# e.blancocarmona@kitz-heidelberg.de
# PhD Student – Clinical Bioinformatics
# Division of Pediatric Neurooncology (B062)

# Read in sample.
sample <- readRDS("/omics/odcf/analysis/OE0145_projects/idh_gliomas/Figures_Science/revision/IDH_gliomas_book/datasets/primary_ATAC_OD.rds")
sample_id <- "Primary ATAC OD"
```



```{r}
sample@meta.data %>% 
dplyr::select(dplyr::all_of(c("orig.ident", "grade", "percentage_reads_in_peaks", "peak_region_fragments", "blacklist_ratio", "TSS.enrichment", "nucleosome_signal"))) %>% 
tibble::as_tibble() %>% 
dplyr::group_by(.data$orig.ident) %>% 
dplyr::reframe("grade" = unique(.data$grade),
               "cells" = dplyr::n(),
               "avg.percentage_reads_in_peaks" = mean(.data$percentage_reads_in_peaks, na.rm = TRUE),
               "avg.peak_region_fragments" = mean(.data$peak_region_fragments, na.rm = TRUE),
               "avg.blacklist_ratio" = mean(.data$blacklist_ratio, na.rm = TRUE),
               "avg.TSS.enrichment" = mean(.data$TSS.enrichment, na.rm = TRUE),
               "avg.nucleosome_signal" = mean(.data$nucleosome_signal, na.rm = TRUE)) %>% 
dplyr::arrange(dplyr::desc(.data$cells), 
               dplyr::desc(.data$avg.percentage_reads_in_peaks)) %>% 
gt::gt()  %>% 
gt::cols_align(columns = c("orig.ident", "grade"),
               align = "center") %>% 
gt::cols_align(columns = c("cells", "avg.percentage_reads_in_peaks", "avg.peak_region_fragments", "avg.blacklist_ratio", "avg.TSS.enrichment", "avg.nucleosome_signal"),
               align = "center") %>% 
gt::tab_style(locations = gt::cells_column_labels(),
              style = list(gt::cell_text(weight = "bold",
                                         v_align = "middle",
                                         align = "center"))) %>% 
gt::tab_style(locations = gt::cells_body(columns = c("cells", "avg.percentage_reads_in_peaks", "avg.peak_region_fragments", "avg.blacklist_ratio", "avg.TSS.enrichment", "avg.nucleosome_signal")),
              style = list(gt::cell_text(style = "italic",
                                         color = "#00798c"))) %>% 
gt::tab_style(locations = gt::cells_title(),
              style = list(gt::cell_text(weight = "bold",
                                         v_align = "middle"))) %>% 
gt::fmt_number(columns = c("cells"), 
               decimals = 0,
               sep_mark = " ",
               dec_mark = ".") %>% 
gt::fmt_number(columns = c("avg.percentage_reads_in_peaks", "avg.peak_region_fragments", "avg.blacklist_ratio", "avg.TSS.enrichment", "avg.nucleosome_signal"), 
               decimals = 2,
               sep_mark = " ",
               dec_mark = ".") %>% 
gt::cols_label(orig.ident = "Patient",
               grade = "LGG grade",
               cells = "Number of cells",
               avg.percentage_reads_in_peaks = "Avg. Pct. Reads in Peaks",
               avg.peak_region_fragments = "Avg. Peak Region Fragments",
               avg.blacklist_ratio = "Avg. Blacklist Ratio",
               avg.TSS.enrichment = "Avg. TSS enrichment Score",
               avg.nucleosome_signal = "Avg. Nucleosome Signal") %>% 
gt::tab_header(title = paste0('QC metrics | ', sample_id),
               subtitle = paste0("N = ", length(unique(sample$orig.ident)))) %>%
gt::opt_stylize(style = 1, color = "cyan")
            
```

```{r}
data <- sample@meta.data %>% 
        dplyr::select(dplyr::all_of(c("orig.ident", "relabelling"))) %>% 
        tibble::as_tibble() %>% 
        dplyr::group_by(.data$orig.ident, .data$relabelling) %>% 
        dplyr::reframe("cells" = dplyr::n()) %>% 
        tidyr::pivot_wider(names_from = "relabelling",
                           values_from = "cells") %>% 
        as.data.frame()

data[is.na(data)] <- 0

data %>% 
gt::gt()  %>% 
gt::cols_align(columns = c("orig.ident"),
               align = "center") %>% 
gt::cols_align(columns = unique(sample$relabelling),
               align = "center") %>% 
gt::tab_style(locations = gt::cells_column_labels(),
              style = list(gt::cell_text(weight = "bold",
                                         v_align = "middle",
                                         align = "center"))) %>% 
gt::tab_style(locations = gt::cells_body(columns = unique(sample$relabelling)),
              style = list(gt::cell_text(style = "italic",
                                         color = "#00798c"))) %>% 
gt::tab_style(locations = gt::cells_title(),
              style = list(gt::cell_text(weight = "bold",
                                         v_align = "middle"))) %>% 
gt::fmt_number(columns = unique(sample$relabelling), 
               decimals = 0,
               sep_mark = " ",
               dec_mark = ".") %>% 
gt::cols_label(orig.ident = "Patient") %>% 
gt::tab_header(title = paste0('Number of cells per cell type and patient | ', sample_id),
               subtitle = paste0("N = ", length(unique(sample$orig.ident)))) %>%
gt::opt_stylize(style = 1, color = "cyan")
            
```

