# Key info {.unnumbered}

Diffuse gliomas harbor recurrent mutations in the isocitrate dehydrogenase (IDH) gene. IDH mutant gliomas are classified into two major subtypes: Oligodendrogliomas with chromosome arms 1p/19q codeletion and astrocytomas with euploid 1p/19q. Recent studies have highlighted intratumoral heterogeneity as a feature of IDH mutant gliomas. These tumors exhibit a hierarchy of cellular phenotypes, with a neural stem cell-like population giving rise to tumor subpopulations with expression signatures resembling astrocytes and oligodendrocytes. However, a detailed comparison of transcriptional and epigenomic heterogeneity in oligodendrogliomas and astrocytomas is still lacking.

In addition, IDH mutant gliomas have distinct activation states of tumor-associated microglia/macrophages (TAMs); however, it is not clear whether TAM composition differs between oligodendrogliomas and astrocytomas, how tumor subpopulations interact with TAMs and to what extent tumor grade and recurrence play a role in promoting TAM diversity in diffuse gliomas. Therefore, comparative analyses of tumor heterogeneity and tumor-stroma interactions are critical to our understanding of IDH mutant gliomas and their evolution.

Here, we performed high-throughput single-nucleus RNA and ATAC sequencing (snRNA- and snATAC-seq) on primary IDH mutant gliomas and snRNA-seq on a cohort of primary and recurrent astrocytoma pairs to create a resource to comprehensively resolve tumor diversity and TAM states. Our results confirm the previously described differentiation hierarchies and reveal a novel group of epigenetically and transcriptionally distinct ribosomal enriched non-cycling stem-like tumor cells in IDH mutant gliomas. We identify significant transcriptional differences in TAM states between oligodendrogliomas and astrocytomas, and receptor-ligand interaction mapping between tumor subpopulations and TAM states reveals a notable interaction between inflammatory TAMs and astrocytic tumor subpopulations in astrocytomas confirmed by immunohistochemical analyses of validation cohorts. These results suggest that TAM-tumor interactions may contribute to the clinical course of oligodendrogliomas and astrocytomas.

## Book contents {.unnumbered}

In the present book, we have compiled all the code used in the analysis and to generate the figures. A couple of notes worth mentioning:

-   Absolute paths are displayed, which will not work on another user's end.
-   Objects are loaded based on such pathways. Another user will have to regenerate such objects based on the available data.
-   Metadata columns may vary between the code and the available metadata. However, this should be a name change.
-   **Development** version of [`SCpubr`](https://github.com/enblacar/SCpubr) was used (equivalent to `v2.X.X`, when published) for the figures.

## Contact {.unnumbered}

Corresponding authors:

-   **Sevin Turcan**: sevin.turcan\@med.uni-heidelberg.de
-   **Holger Heyn**: holger.heyn\@cnag.eu

For any queries on the figures, please contact:

-   **Enrique Blanco Carmona**: e.blancocarmona\@kitz-heidelberg.de
-   If related to `SCpubr`: https://github.com/enblacar/SCpubr/issues/new/choose
